Multiple fixes. (#333)
* Updated ahoy commands + added redis.

* Fixed lagoon supprot in drush aliases files + fixed coding standards.

* Fixed Behat tests entering CLI on test fail.

* Added Doctor.

* Added hiding of dev-install.

* Added Brewfile.

* Updated  volumes in docker-compose.

* Fixed ahoy config.

* Added back .env file.

* Updated sanitize comments.

* Fixed Acquia db update hook.

* Fixed local url to correctly handle hyphens and spaces in ptoject name + fixed FTP.

* Fixed indentaion in docker compose.

* More fixes.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -2,16 +2,29 @@
 ahoyapi: v2
 
 commands:
+
   # Docker commands.
+  build:
+    usage: Build or rebuild project.
+    cmd: |
+      ahoy title "Building project" \
+      && ahoy clean \
+      && (docker network prune -f > /dev/null && docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network) \
+      && ahoy up -- --build --force-recreate \
+      && ahoy install-dev \
+      && ahoy install-site \
+      && ahoy title "Build complete" \
+      && ahoy info 1
+
   info:
     usage: Print information about this project.
     cmd: |
       ahoy line "Site URL              : " ${LOCALDEV_URL}
       ahoy line "Path to project       : " ${APP}
-      ahoy line "Path to docroot       : " ${DOCROOT}
-      ahoy line "DB port on host       : " $(docker-compose port mariadb 3306 | cut -d : -f 2)
+      ahoy line "Path to docroot       : " ${APP}/${WEBROOT}
+      ahoy line "DB port on host       : " $(docker port $(docker-compose ps -q mariadb) 3306 | cut -d : -f 2)
       # [META:SOLR]
-      ahoy line "Solr port on host     : " $(docker-compose port solr 8983 | cut -d : -f 2)
+      ahoy line "Solr port on host     : " $(docker port $(docker-compose ps -q solr) 8983 | cut -d : -f 2)
       # [/META:SOLR]
       ahoy line "Mailhog URL           : " http://mailhog.docker.amazee.io/
       if [ "$1" ]; then
@@ -19,16 +32,16 @@ commands:
       fi
 
   up:
-    usage: Build and start Docker containers
+    usage: Build and start Docker containers.
     cmd: |
-      docker-compose up -d "$@"
-      ahoy cli "dockerize -wait tcp://mariadb:3306 -timeout 1m"
-      if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi
-      docker ps -a --filter name=^/${COMPOSE_PROJECT_NAME}_
+      docker-compose up -d "$@" \
+      && ahoy cli "dockerize -wait tcp://mariadb:3306 -timeout 1m" \
+      && if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi \
+      && docker ps -a --filter name=^/${COMPOSE_PROJECT_NAME}_
 
   down:
     usage: Stop Docker containers and remove container, images, volumes and networks.
-    cmd: docker-compose down
+    cmd: docker-compose down --volumes
 
   start:
     usage: Start existing Docker containers.
@@ -52,18 +65,20 @@ commands:
 
   cli:
     usage: Start a shell inside CLI container or run a command.
-    cmd: if \[ "$@" \]; then docker-compose exec cli bash -c "$@"; else docker-compose exec cli bash; fi
+    cmd: if \[ "$@" \]; then docker exec -i $(docker-compose ps -q cli) bash -c "$@"; else docker exec -it $(docker-compose ps -q cli) bash; fi
 
   drush:
     usage: Run drush commands in the CLI service container.
-    cmd: docker-compose exec -T cli drush -r ${DOCROOT} -l ${LOCALDEV_URL} "$@"
+    cmd: docker exec -i $(docker-compose ps -q cli) drush -r ${APP}/${WEBROOT} -l ${LOCALDEV_URL} "$@"
 
   # Application commands.
   login:
     usage: Login to a website.
-    cmd: |
-      ahoy drush uublk 1 -q
-      ahoy drush uli "$@"
+    cmd: ahoy drush uublk 1 -q && ahoy drush uli "$@"
+
+  doctor:
+    usage: Find problems with current project setup.
+    cmd: scripts/doctor.sh
 
   download-db:
     usage: Download database.
@@ -80,10 +95,10 @@ commands:
       # [/META:ACQUIA]
       # [META:FTP]
       # Download DB dump from FTP. Remove if site install is used.
-      #### mkdir -p ${DATAROOT} && curl -u ${FTP_USER}:${FTP_PASS} "ftp://${FTP_HOST}/${FTP_FILE}" -o ${DATAROOT}/db.sql
+      #### mkdir -p ${DATAROOT} && curl -u ${FTP_USER}:${FTP_PASS} "ftp://${FTP_HOST}:${FTP_PORT}/${FTP_FILE}" -o ${DATAROOT}/db.sql
       # [/META:FTP]
 
-  install:
+  install-site:
     usage: Install a site.
     cmd: |
       ahoy title "Importing database from the dump"
@@ -95,7 +110,7 @@ commands:
       # [META:PROFILE]
       # Replace lines above with lines below if you want to install site from profile.
       # ahoy title "Installing a site from profile"
-      # ahoy drush si ${INSTALL_PROFILE} -y --account-name=admin --site-name="MYSITE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
+      # ahoy drush si ${DRUPAL_PROFILE} -y --account-name=admin --site-name="MYSITE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
       # ahoy drush en -y mysite_core
       # [/META:PROFILE]
       # [META]
@@ -110,7 +125,8 @@ commands:
       ahoy drush sql-drop -y
       ahoy cli "mkdir -p /tmp/.data"
       docker cp -L ${DATAROOT}/db.sql $(docker-compose ps -q cli):/tmp/.data/db.sql
-      ahoy cli "bash -c \"drush -r ${DOCROOT} sql-cli < /tmp/.data/db.sql\""
+      ahoy cli "bash -c \"drush -r ${APP}/${WEBROOT} sql-cli < /tmp/.data/db.sql\""
+    hide: true
 
   export-db:
     usage: Export database dump.
@@ -132,29 +148,24 @@ commands:
         docker cp -L ${DB_SANITIZE_SQL} $(docker-compose ps -q cli):/tmp/${DB_SANITIZE_SQL}
         ahoy drush sql-query --file=/tmp/${DB_SANITIZE_SQL}
       fi
+    hide: true
 
   clean:
-    usage: Clean project
+    usage: Remove all build files.
     cmd: |
-      ahoy down
-      # chmod -Rf 777 docroot/sites/default
-      [ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs chmod -Rf 777
-      [ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs rm -Rf
-      rm -Rf vendor
-      rm -Rf node_modules
-      rm -Rf screenshots
+      ahoy down \
+      && ([ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs chmod -Rf 777 || true) \
+      && ([ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs rm -Rf || true) \
+      && rm -Rf vendor \
+      rm -Rf node_modules \
+      && rm -Rf screenshots
 
-  build:
-    usage: Build or rebuild project.
+  clean-full:
+    usage: Remove all development files.
     cmd: |
-      ahoy title "Building project"
-      ahoy clean
-      ahoy up -- --build --force-recreate
-      ahoy install-dev
-      ahoy install
-      ahoy fe
-      ahoy title "Build complete"
-      ahoy info 1
+      ahoy clean \
+      && ([ -d .git ] && git ls-files --directory --other . | grep -v ".idea" | xargs chmod -Rf 777 || true) \
+      && ([ -d .git ] && git ls-files --directory --other . | grep -v ".idea" | xargs rm -Rf || true)
 
   fe:
     usage: Build front-end assets.
@@ -173,12 +184,17 @@ commands:
     cmd: |
       ahoy cli "composer install -n --ansi --prefer-dist --no-suggest"
       ahoy cli "npm install"
+    hide: true
+
+  flush-redis:
+    usage: Flush Redis cache.
+    cmd: docker exec -i $(docker-compose ps -q redis) redis-cli flushall > /dev/null
 
   lint:
     usage: Lint code.
     cmd: |
       ahoy cli "vendor/bin/parallel-lint --exclude vendor --exclude node_modules -e ${PHP_LINT_EXTENSIONS} ${PHP_LINT_TARGETS//,/ }" \
-      && ahoy cli "vendor/bin/phpcs" \
+      && ahoy cli "vendor/bin/phpcs ${PHPCS_TARGETS}" \
       && ahoy cli "npm run lint"
 
   test:
@@ -215,10 +231,18 @@ commands:
     hide: true
 
 entrypoint:
-- bash
-- "-c"
-- |
-  [ -f .env ] && export $(grep -v '^#' .env | xargs) && [ -f .env.local ] && export $(grep -v '^#' .env.local | xargs)
-  bash -c "$0" "$@"
-- '{{cmd}}'
-- '{{name}}'
+  - bash
+  - "-c"
+  - |
+    [ -f .env ] && export $(grep -v '^#' .env | xargs) && [ -f .env.local ] && export $(grep -v '^#' .env.local | xargs)
+    export PROJECT_NAME=${PROJECT_NAME:-$(basename $(pwd))}
+    export LOCALDEV_URL=${LOCALDEV_URL:-http://${PROJECT_NAME/[_ ]/-}.docker.amazee.io}
+    export PHPCS_TARGETS=${PHPCS_TARGETS//,/ }
+    # [META]
+    # Location of the dummy database used for demonstration only.
+    # This will be removed during project init.
+    export DUMMY_DB=https://goo.gl/bdZ2Zj
+    # [/META]
+    bash -c "$0" "$@"
+  - '{{cmd}}'
+  - '{{name}}'
