Updated ahoy commands + added redis.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -1,17 +1,130 @@
 ---
 ahoyapi: v2
 
+entrypoint:
+  - bash
+  - "-c"
+  - |
+    [ -f .env ] && export $(grep -v '^#' .env | xargs) && [ -f .env.local ] && export $(grep -v '^#' .env.local | xargs)
+
+    # Variables to control project functionality.
+    #
+    # You may create .env file and override the variables below for your project
+    # and then commit this file.
+    #
+    # You may also create .env.local file to override any values locally (it is
+    # excluded from git).
+
+    # Project name.
+    # Defaults to the name of the current directory with stripped hyphens and
+    # underscores.
+    export PROJECT_NAME=${PROJECT_NAME:-$(basename $(pwd))}
+
+    # Docker Compose project name.
+    # All containers will have this prefix.
+    # Defaults to $PROJECT_NAME.
+    export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-$PROJECT_NAME}
+
+    # Path to the root of the project inside of the container.
+    export APP=${APP:-/app}
+
+    # Path to the site installation relative to the current directory.
+    export WEBROOT=${WEBROOT:-docroot}
+
+    # Path to the data directory relative to the current directory.
+    export DATAROOT=${DATAROOT:-.data}
+
+    # Path to a file with additional sanitization commands.
+    export DB_SANITIZE_SQL=${DB_SANITIZE_SQL:-.drupal-dev/sanitize.sql}
+
+    # Flag to enable DB exporting before importing. Useful to backup DB during development.
+    export DB_EXPORT_BEFORE_IMPORT=${DB_EXPORT_BEFORE_IMPORT:-}
+
+    # Local development URL.
+    # Make sure that there is no trailing slash in the value.
+    # Defaults to http://<CURRENTDIR>.docker.amazee.io
+    export LOCALDEV_URL=${LOCALDEV_URL:-http://${PROJECT_NAME/[_]/}.docker.amazee.io}
+
+    # Database connection details.
+    export MYSQL_HOST=${MYSQL_HOST:-mariadb}
+    export MYSQL_PORT=${MYSQL_PORT:-3306}
+
+    # Drupal profile name. Uncomment this for site build and set the profile name.
+    export DRUPAL_PROFILE=${DRUPAL_PROFILE:-}
+
+    # Drupal module prefix for site-specific modules.
+    export DRUPAL_MODULE_PREFIX=${DRUPAL_MODULE_PREFIX:-mysite}
+
+    # Comma-separated list of PHPCS targets (no spaces).
+    PHPCS_TARGETS=${PHPCS_TARGETS:-} && export PHPCS_TARGETS=${PHPCS_TARGETS//,/ }
+
+    # PHP Parallel Lint extensions as a comma-separated list of extensions with
+    # no preceding dot or space.
+    PHP_LINT_EXTENSIONS=${PHP_LINT_EXTENSIONS:-php,inc,module,theme,install}
+    # PHP Parallel Lint targets as a comma-separated list of extensions with no
+    # preceding dot or space.
+    PHP_LINT_TARGETS="tests,docroot/profiles/custom/mysite_profile,docroot/modules/custom,docroot/themes/custom,docroot/sites/default/settings.php"
+
+    # [META:LAGOON]
+    # Flag to expect configured Lagoon integration. Once Lagoon integration is
+    # implemented, change this to 1 in order to have access to Lagoon environments
+    # from CLI.
+    export LAGOON_INTEGRATION_ENABLED=${LAGOON_INTEGRATION_ENABLED:-}
+    # [/META:LAGOON]
+
+    # [META:ACQUIA]
+    # Acquia Cloud settings to download DB from backup.
+    # @see https://cloudapi.acquia.com/#GET__sites__site_envs__env_dbs__db_backups__backup_download-instance_route
+    export AC_API_DB_SITE=${AC_API_DB_SITE:-devcloud:mysite}
+    export AC_API_DB_ENV=${AC_API_DB_ENV:-prod}
+    export AC_API_DB_NAME=${AC_API_DB_NAME:-mysite}
+    export AC_API_USER_NAME=${AC_API_USER_NAME:-}
+    export AC_API_USER_PASS=${AC_API_USER_PASS:-}
+    # [/META:ACQUIA]
+
+    # [META:FTP]
+    # FTP details to download the DB from.
+    # Note that for CI, these variables should be set trough UI.
+    FTP_HOST=${FTP_HOST:-}
+    FTP_USER=${FTP_USER:-}
+    FTP_PASS=${FTP_PASS:-}
+    FTP_FILE=${FTP_FILE:-db.sql}
+    # [/META:FTP]
+
+    # [META]
+    # Location of the dummy database used for demonstration only.
+    # This will be removed during project init.
+    DUMMY_DB=https://goo.gl/bdZ2Zj
+    # [/META]
+
+    bash -c "$0" "$@"
+  - '{{cmd}}'
+  - '{{name}}'
+
 commands:
+
   # Docker commands.
+  build:
+    usage: Build or rebuild project.
+    cmd: |
+      ahoy title "Building project" \
+      && ahoy clean \
+      && (docker network prune -f > /dev/null && docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network) \
+      && ahoy up -- --build --force-recreate \
+      && ahoy install-dev \
+      && ahoy install-site \
+      && ahoy title "Build complete" \
+      && ahoy info 1
+
   info:
     usage: Print information about this project.
     cmd: |
       ahoy line "Site URL              : " ${LOCALDEV_URL}
       ahoy line "Path to project       : " ${APP}
-      ahoy line "Path to docroot       : " ${DOCROOT}
-      ahoy line "DB port on host       : " $(docker-compose port mariadb 3306 | cut -d : -f 2)
+      ahoy line "Path to docroot       : " ${APP}/${WEBROOT}
+      ahoy line "DB port on host       : " $(docker port $(docker-compose ps -q mariadb) 3306 | cut -d : -f 2)
       # [META:SOLR]
-      ahoy line "Solr port on host     : " $(docker-compose port solr 8983 | cut -d : -f 2)
+      ahoy line "Solr port on host     : " $(docker port $(docker-compose ps -q solr) 8983 | cut -d : -f 2)
       # [/META:SOLR]
       ahoy line "Mailhog URL           : " http://mailhog.docker.amazee.io/
       if [ "$1" ]; then
@@ -21,14 +134,14 @@ commands:
   up:
     usage: Build and start Docker containers
     cmd: |
-      docker-compose up -d "$@"
-      ahoy cli "dockerize -wait tcp://mariadb:3306 -timeout 1m"
-      if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi
-      docker ps -a --filter name=^/${COMPOSE_PROJECT_NAME}_
+      docker-compose up -d "$@" \
+      && ahoy cli "dockerize -wait tcp://mariadb:3306 -timeout 1m" \
+      && if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi \
+      && docker ps -a --filter name=^/${COMPOSE_PROJECT_NAME}_ &&
 
   down:
     usage: Stop Docker containers and remove container, images, volumes and networks.
-    cmd: docker-compose down
+    cmd: docker-compose down --volumes
 
   start:
     usage: Start existing Docker containers.
@@ -52,38 +165,36 @@ commands:
 
   cli:
     usage: Start a shell inside CLI container or run a command.
-    cmd: if \[ "$@" \]; then docker-compose exec cli bash -c "$@"; else docker-compose exec cli bash; fi
+    cmd: if \[ "$@" \]; then docker exec -i $(docker-compose ps -q cli) bash -c "$@"; else docker exec -it $(docker-compose ps -q cli) bash; fi
 
   drush:
     usage: Run drush commands in the CLI service container.
-    cmd: docker-compose exec -T cli drush -r ${DOCROOT} -l ${LOCALDEV_URL} "$@"
+    cmd: docker exec -i $(docker-compose ps -q cli) drush -r ${APP}/${WEBROOT} -l ${LOCALDEV_URL} "$@"
 
   # Application commands.
   login:
     usage: Login to a website.
-    cmd: |
-      ahoy drush uublk 1 -q
-      ahoy drush uli "$@"
+    cmd: ahoy drush uublk 1 -q && ahoy drush uli "$@"
 
   download-db:
     usage: Download database.
     cmd: |
-      ahoy title "Downloading database"
+      ahoy title "Downloading database" \
       # [META]
       # Download dummy DB.
       # Used for demonstration purposes. This line is removed during project init.
-      mkdir -p ${DATAROOT} && curl -L ${DUMMY_DB} -o ${DATAROOT}/db.sql
+      && mkdir -p ${DATAROOT} && curl -L ${DUMMY_DB} -o ${DATAROOT}/db.sql \
       # [/META]
       # [META:ACQUIA]
       # Download DB from Acquia Cloud backup. Remove if site install is used.
-      #### AC_API_USER_NAME=${AC_API_USER_NAME} AC_API_USER_PASS=${AC_API_USER_PASS} AC_API_DB_SITE=${AC_API_DB_SITE} AC_API_DB_ENV=${AC_API_DB_ENV} AC_API_DB_NAME=${AC_API_DB_NAME} DB_REMOVE_CACHED_DUMPS=${DB_REMOVE_CACHED_DUMPS} ./scripts/download-backup-acquia.sh
+      #### && AC_API_USER_NAME=${AC_API_USER_NAME} AC_API_USER_PASS=${AC_API_USER_PASS} AC_API_DB_SITE=${AC_API_DB_SITE} AC_API_DB_ENV=${AC_API_DB_ENV} AC_API_DB_NAME=${AC_API_DB_NAME} DB_REMOVE_CACHED_DUMPS=${DB_REMOVE_CACHED_DUMPS} ./scripts/download-backup-acquia.sh
       # [/META:ACQUIA]
       # [META:FTP]
       # Download DB dump from FTP. Remove if site install is used.
-      #### mkdir -p ${DATAROOT} && curl -u ${FTP_USER}:${FTP_PASS} "ftp://${FTP_HOST}/${FTP_FILE}" -o ${DATAROOT}/db.sql
+      #### && mkdir -p ${DATAROOT} && curl -u ${FTP_USER}:${FTP_PASS} "ftp://${FTP_HOST}/${FTP_FILE}" -o ${DATAROOT}/db.sql
       # [/META:FTP]
 
-  install:
+  install-site:
     usage: Install a site.
     cmd: |
       ahoy title "Importing database from the dump"
@@ -95,7 +206,7 @@ commands:
       # [META:PROFILE]
       # Replace lines above with lines below if you want to install site from profile.
       # ahoy title "Installing a site from profile"
-      # ahoy drush si ${INSTALL_PROFILE} -y --account-name=admin --site-name="MYSITE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
+      # ahoy drush si ${DRUPAL_PROFILE} -y --account-name=admin --site-name="MYSITE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
       # ahoy drush en -y mysite_core
       # [/META:PROFILE]
       # [META]
@@ -111,6 +222,7 @@ commands:
       ahoy cli "mkdir -p /tmp/.data"
       docker cp -L ${DATAROOT}/db.sql $(docker-compose ps -q cli):/tmp/.data/db.sql
       ahoy cli "bash -c \"drush -r ${DOCROOT} sql-cli < /tmp/.data/db.sql\""
+    hide: true
 
   export-db:
     usage: Export database dump.
@@ -132,29 +244,24 @@ commands:
         docker cp -L ${DB_SANITIZE_SQL} $(docker-compose ps -q cli):/tmp/${DB_SANITIZE_SQL}
         ahoy drush sql-query --file=/tmp/${DB_SANITIZE_SQL}
       fi
+    hide: true
 
   clean:
-    usage: Clean project
+    usage: Remove all build files.
     cmd: |
-      ahoy down
-      # chmod -Rf 777 docroot/sites/default
-      [ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs chmod -Rf 777
-      [ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs rm -Rf
-      rm -Rf vendor
-      rm -Rf node_modules
-      rm -Rf screenshots
+      ahoy down \
+      && ([ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs chmod -Rf 777 || true) \
+      && ([ -d .git ] && git ls-files --directory --other -i --exclude-from=.gitignore ${WEBROOT} | grep -v "settings.local.php" | grep -v "services.local.yml" | xargs rm -Rf || true) \
+      && rm -Rf vendor \
+      rm -Rf node_modules \
+      && rm -Rf screenshots
 
-  build:
-    usage: Build or rebuild project.
+  clean-full:
+    usage: Remove all development files.
     cmd: |
-      ahoy title "Building project"
-      ahoy clean
-      ahoy up -- --build --force-recreate
-      ahoy install-dev
-      ahoy install
-      ahoy fe
-      ahoy title "Build complete"
-      ahoy info 1
+      ahoy clean \
+      && ([ -d .git ] && git ls-files --directory --other . | grep -v ".idea" | xargs chmod -Rf 777 || true) \
+      && ([ -d .git ] && git ls-files --directory --other . | grep -v ".idea" | xargs rm -Rf || true)
 
   fe:
     usage: Build front-end assets.
@@ -174,11 +281,15 @@ commands:
       ahoy cli "composer install -n --ansi --prefer-dist --no-suggest"
       ahoy cli "npm install"
 
+  flush-redis:
+    usage: Flush Redis cache.
+    cmd: docker exec -i $(docker-compose ps -q redis) redis-cli flushall > /dev/null
+
   lint:
     usage: Lint code.
     cmd: |
       ahoy cli "vendor/bin/parallel-lint --exclude vendor --exclude node_modules -e ${PHP_LINT_EXTENSIONS} ${PHP_LINT_TARGETS//,/ }" \
-      && ahoy cli "vendor/bin/phpcs" \
+      && ahoy cli "vendor/bin/phpcs ${PHPCS_TARGETS}" \
       && ahoy cli "npm run lint"
 
   test:
@@ -213,12 +324,3 @@ commands:
   line:
     cmd: printf "$(tput -Txterm setaf 2)${1}$(tput -Txterm sgr0)${2}\n"
     hide: true
-
-entrypoint:
-- bash
-- "-c"
-- |
-  [ -f .env ] && export $(grep -v '^#' .env | xargs) && [ -f .env.local ] && export $(grep -v '^#' .env.local | xargs)
-  bash -c "$0" "$@"
-- '{{cmd}}'
-- '{{name}}'
