feat: Added support for Docker Compose v2.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -32,8 +32,8 @@ commands:
     usage: Show information about this project.
     cmd: |
       COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-${PWD##*/}} \
-      DREVOPS_HOST_DB_PORT=$(docker port $(docker-compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2) \
-      DREVOPS_HOST_SOLR_PORT=$(docker port $(docker-compose ps -q solr 2>/dev/null) 8983 2>/dev/null | cut -d : -f 2) \
+      DREVOPS_HOST_DB_PORT=$(docker compose port mariadb 3306 2>/dev/null | cut -d : -f 2) \
+      DREVOPS_HOST_SOLR_PORT=$(docker compose port solr 8983 2>/dev/null | cut -d : -f 2) \
       DREVOPS_DRUPAL_SHOW_LOGIN_LINK=${DREVOPS_DRUPAL_SHOW_LOGIN_LINK} \
       ahoy cli ./scripts/drevops/info.sh "$@"
 
@@ -41,7 +41,7 @@ commands:
     usage: Open DB in Sequel Ace.
     cmd: |
       uname -a | grep -i -q darwin && mdfind -name 'Sequel Ace' 2>/dev/null |grep -q "Ace" \
-      && DREVOPS_HOST_DB_PORT="$(docker port $(docker-compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2)" \
+      && DREVOPS_HOST_DB_PORT="$(docker port $(docker compose ps -q mariadb 2>/dev/null) 3306 2>/dev/null | cut -d : -f 2)" \
       && open "mysql://${DREVOPS_MARIADB_USER}:${DREVOPS_MARIADB_PASSWORD}@127.0.0.1:${DREVOPS_HOST_DB_PORT}/drupal" -a "Sequel Ace" \
       || echo "Not a supported OS or Sequel Ace is not installed."
 
@@ -52,32 +52,32 @@ commands:
   up:
     usage: Build and start Docker containers.
     cmd: |
-      docker-compose up -d "$@" && if docker-compose logs | grep -q "\[Error\]"; then exit 1; fi
-      mkdir -p ${DREVOPS_WEBROOT}/sites/default/files && docker-compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > ${DREVOPS_APP}/${DREVOPS_WEBROOT}/sites/default/files/livereload.sock'
+      docker compose up -d "$@" && if docker compose logs | grep -q "\[Error\]"; then exit 1; fi
+      mkdir -p ${DREVOPS_WEBROOT}/sites/default/files && docker compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > ${DREVOPS_APP}/${DREVOPS_WEBROOT}/sites/default/files/livereload.sock'
 
   down:
     usage: Stop Docker containers and remove container, images, volumes and networks.
     cmd: |
       ahoy confirm "Running this command will remove your current database. Are you sure?" &&
-      if [ -f "docker-compose.yml" ]; then docker-compose down --remove-orphans --volumes > /dev/null 2>&1; fi
+      if [ -f "docker-compose.yml" ]; then docker compose down --remove-orphans --volumes > /dev/null 2>&1; fi
 
   start:
     usage: Start existing Docker containers.
     cmd: |
-      docker-compose start "$@"
-      mkdir -p ${DREVOPS_WEBROOT}/sites/default/files && docker-compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > ${DREVOPS_APP}/${DREVOPS_WEBROOT}/sites/default/files/livereload.sock'
+      docker compose start "$@"
+      mkdir -p ${DREVOPS_WEBROOT}/sites/default/files && docker compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > ${DREVOPS_APP}/${DREVOPS_WEBROOT}/sites/default/files/livereload.sock'
 
   stop:
     usage: Stop running Docker containers.
-    cmd: docker-compose stop "$@"
+    cmd: docker compose stop "$@"
 
   restart:
     usage: Restart stopped or running Docker containers.
-    cmd: docker-compose restart "$@"
+    cmd: docker compose restart "$@"
 
   logs:
     usage: Show Docker logs for services.
-    cmd: docker-compose logs "$@"
+    cmd: docker compose logs "$@"
 
   pull:
     usage: Pull latest Docker images.
@@ -90,7 +90,7 @@ commands:
     # environment variables will be started. This allows passing of the environment
     # variables to Ahoy commands which will then be forwarded to the container.
     # Escape double quotes with \" (slash double-quote) when passing arguments with spaces.
-    cmd: if \[ "${#}" -ne 0 \]; then docker-compose exec $(env | cut -f1 -d= | grep "DREVOPS_\|COMPOSE_\|TERM" | sed 's/^/-e /') -T cli bash -c "$*"; else docker-compose exec cli bash; fi
+    cmd: if \[ "${#}" -ne 0 \]; then docker compose exec $(env | cut -f1 -d= | grep "DREVOPS_\|COMPOSE_\|TERM" | sed 's/^/-e /') -T cli bash -c "$*"; else docker compose exec cli bash; fi
 
   composer:
     usage: Run Composer commands in the CLI service container.
@@ -98,12 +98,12 @@ commands:
 
   drush:
     usage: Run Drush commands in the CLI service container.
-    cmd: ahoy cli "drush -l ${DREVOPS_LOCALDEV_URL} $*"
+    cmd: ahoy cli "drush -l \${DREVOPS_LOCALDEV_URL} $*"
 
   #;< REDIS
   flush-redis:
     usage: Flush Redis cache.
-    cmd: docker-compose exec redis redis-cli flushall
+    cmd: docker compose exec redis redis-cli flushall
   #;> REDIS
 
   # ----------------------------------------------------------------------------
@@ -125,9 +125,10 @@ commands:
     usage: Reload the database container using local database image.
     cmd: |
       ahoy confirm "Running this command will replace your current database. Are you sure?" &&
-      docker-compose rm -f -s -v mariadb \
+      docker compose rm -f -s -v mariadb \
         && ahoy up -- --build mariadb \
         && ahoy up wait_dependencies \
+        && sleep 15 \
         && ahoy install-site \
         && ahoy info \
         && ahoy login
@@ -264,7 +265,7 @@ entrypoint:
   #:
   #: It is important to understand that variables set in .env file are already
   #: available inside the containers after stack is running (as a part of
-  #: docker-compose functionality), so most of the commands are using these
+  #: docker compose functionality), so most of the commands are using these
   #: values taken from containers.
   #:
   #: However, since Docker does not support changes to environment variables in
