Fixed ahoy commands not failing the build.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -7,15 +7,15 @@ commands:
   build:
     usage: Build or rebuild project.
     cmd: |
-      ahoy title "Building project" && \
-      ahoy pre-flight && \
-      ahoy clean && \
-      (docker network prune -f > /dev/null && docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network) && \
-      ahoy up -- --build --force-recreate && \
-      (if [ "${BUILD_EXPORT_DIR}" != "" ]; then mkdir -p ${BUILD_EXPORT_DIR} && docker cp -L $(docker-compose ps -q cli):/app/. ${BUILD_EXPORT_DIR}; rm -Rf ${BUILD_EXPORT_DIR}/node_modules >/dev/null; fi) && \
-      ahoy install-dev && \
-      ahoy install-site && \
-      ahoy title "Build complete" && \
+      ahoy title "Building project"
+      ahoy pre-flight
+      ahoy clean
+      (docker network prune -f > /dev/null && docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network)
+      ahoy up -- --build --force-recreate
+      (if [ "${BUILD_EXPORT_DIR}" != "" ]; then mkdir -p ${BUILD_EXPORT_DIR} && docker cp -L $(docker-compose ps -q cli):/app/. ${BUILD_EXPORT_DIR}; rm -Rf ${BUILD_EXPORT_DIR}/node_modules >/dev/null; fi)
+      ahoy install-dev
+      ahoy install-site
+      ahoy title "Build complete"
       ahoy info 1
 
   info:
@@ -37,9 +37,9 @@ commands:
   up:
     usage: Build and start Docker containers.
     cmd: |
-      docker-compose up -d "$@" && \
-      ahoy cli "dockerize -wait tcp://mariadb:3306 -timeout 1m" && \
-      if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi && \
+      docker-compose up -d "$@"
+      ahoy cli "dockerize -wait tcp://mariadb:3306 -timeout 1m"
+      if docker-compose logs | grep -q "\[Error\]"; then docker-compose logs; exit 1; fi
       docker ps -a --filter name=^/${COMPOSE_PROJECT_NAME}_
 
   down:
@@ -106,42 +106,42 @@ commands:
     usage: Install a site.
     cmd: |
       #;< !FRESH_INSTALL \
-      ahoy title "Installing site from existing database dump" && \
-      (if [ "$DB_EXPORT_BEFORE_IMPORT" != "0" ]; then ahoy export-db; fi) && \
-      ahoy import-db-dump && \
-      (if [ "${SKIP_SANITIZE_DB}" != "1" ]; then ahoy sanitize-db "${site}"; fi) && \
+      ahoy title "Installing site from existing database dump"
+      (if [ "$DB_EXPORT_BEFORE_IMPORT" != "0" ]; then ahoy export-db; fi)
+      ahoy import-db-dump
+      (if [ "${SKIP_SANITIZE_DB}" != "1" ]; then ahoy sanitize-db "${site}"; fi)
       {
         if [ "${SKIP_POST_IMPORT}" != "1" ]; then
-          ahoy drush en your_site_core -y && \
+          ahoy drush en your_site_core -y
           ahoy drush updb -y
         fi
       }
       #;> !FRESH_INSTALL \
       #;< FRESH_INSTALL \
-      ahoy title "Installing a fresh site from ${DRUPAL_PROFILE} profile" && \
-      ahoy drush si "${DRUPAL_PROFILE}" -y --account-name=admin --site-name="YOURSITE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL && \
-      ahoy drush en -y your_site_core && \
+      ahoy title "Installing a fresh site from ${DRUPAL_PROFILE} profile"
+      ahoy drush si "${DRUPAL_PROFILE}" -y --account-name=admin --site-name="YOURSITE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
+      ahoy drush en -y your_site_core
       #;> FRESH_INSTALL \
-      (if ls config/default/*.yml > /dev/null 2>&1; then ahoy title "Importing configuration" && ahoy drush cim -y; fi) && \
+      (if ls config/default/*.yml > /dev/null 2>&1; then ahoy title "Importing configuration" && ahoy drush cim -y; fi)
       ahoy drush cr
 
   import-db-dump:
     usage: Import database dump.
     cmd: |
-      ahoy drush sql-drop -y && \
-      ahoy cli "mkdir -p /tmp/.data" && \
-      docker cp -L ${DATAROOT}/db.sql $(docker-compose ps -q cli):/tmp/.data/db.sql && \
+      ahoy drush sql-drop -y
+      ahoy cli "mkdir -p /tmp/.data"
+      docker cp -L ${DATAROOT}/db.sql $(docker-compose ps -q cli):/tmp/.data/db.sql
       docker-compose exec cli bash -c "pv /tmp/.data/db.sql | drush -r ${APP}/${WEBROOT} sql-cli"
     hide: true
 
   export-db:
     usage: Export database dump.
     cmd: |
-      ahoy cli "mkdir -p /tmp/.data" && \
-      ahoy drush sql-dump --skip-tables-key=common --result-file=/tmp/.data/db.sql -q && \
-      mkdir -p ${DATAROOT} && \
-      DUMP_FILE=$([ "${1}" ] && echo ${DATAROOT}/${1} || echo ${DATAROOT}/db_export_$(date +%Y_%m_%d_%H_%M_%S).sql) && \
-      docker cp -L $(docker-compose ps -q cli):/tmp/.data/db.sql ${DUMP_FILE} && \
+      ahoy cli "mkdir -p /tmp/.data"
+      ahoy drush sql-dump --skip-tables-key=common --result-file=/tmp/.data/db.sql -q
+      mkdir -p ${DATAROOT}
+      DUMP_FILE=$([ "${1}" ] && echo ${DATAROOT}/${1} || echo ${DATAROOT}/db_export_$(date +%Y_%m_%d_%H_%M_%S).sql)
+      docker cp -L $(docker-compose ps -q cli):/tmp/.data/db.sql ${DUMP_FILE}
       [ -f "${DUMP_FILE}" ] && ahoy title "Dump saved to file ${DUMP_FILE}"
 
   sanitize-db:
@@ -149,9 +149,9 @@ commands:
     cmd: |
       ahoy drush sql-sanitize --sanitize-password=password --sanitize-email=user+%uid@localhost -y
       if [ "${DB_SANITIZE_SQL}" != "" ] && [ -f "${DB_SANITIZE_SQL}" ]; then
-        ahoy title "Applying custom sanitization commands" && \
-        ahoy cli "mkdir -p $(dirname /tmp/${DB_SANITIZE_SQL})" && \
-        docker cp -L ${DB_SANITIZE_SQL} $(docker-compose ps -q cli):/tmp/${DB_SANITIZE_SQL} && \
+        ahoy title "Applying custom sanitization commands"
+        ahoy cli "mkdir -p $(dirname /tmp/${DB_SANITIZE_SQL})"
+        docker cp -L ${DB_SANITIZE_SQL} $(docker-compose ps -q cli):/tmp/${DB_SANITIZE_SQL}
         ahoy drush sql-query --file=/tmp/${DB_SANITIZE_SQL}
       fi
     hide: true
@@ -195,11 +195,11 @@ commands:
   install-dev:
     usage: Install dependencies.
     cmd: |
-      if [ -d .data ]; then docker cp -L .data $(docker-compose ps -q cli):/app/; fi && \
-      docker cp -L behat.yml $(docker-compose ps -q cli):/app/ && \
-      docker cp -L tests $(docker-compose ps -q cli):/app/ && \
-      docker cp -L phpcs.xml $(docker-compose ps -q cli):/app/ && \
-      ahoy cli "composer install -n --ansi --prefer-dist --no-suggest" && \
+      if [ -d .data ]; then docker cp -L .data $(docker-compose ps -q cli):/app/; fi
+      docker cp -L behat.yml $(docker-compose ps -q cli):/app/
+      docker cp -L tests $(docker-compose ps -q cli):/app/
+      docker cp -L phpcs.xml $(docker-compose ps -q cli):/app/
+      ahoy cli "composer install -n --ansi --prefer-dist --no-suggest"
       ahoy cli "npm install"
     hide: true
 
@@ -210,15 +210,15 @@ commands:
   lint:
     usage: Lint code.
     cmd: |
-      ahoy cli "vendor/bin/parallel-lint --exclude vendor --exclude node_modules -e ${PHP_LINT_EXTENSIONS} ${PHP_LINT_TARGETS//,/ }" && \
-      ahoy cli "vendor/bin/phpcs -v ${PHPCS_TARGETS//,/ }" && \
+      ahoy cli "vendor/bin/parallel-lint --exclude vendor --exclude node_modules -e ${PHP_LINT_EXTENSIONS} ${PHP_LINT_TARGETS//,/ }"
+      ahoy cli "vendor/bin/phpcs -v ${PHPCS_TARGETS//,/ }"
       ahoy cli "npm run lint" || \
       [ "${ALLOW_LINT_FAIL:-0}" -eq 1 ]
 
   test:
     usage: Run all tests.
     cmd: |
-      ahoy test-phpunit && \
+      ahoy test-phpunit
       ahoy test-behat
 
   test-behat:
@@ -254,12 +254,12 @@ commands:
     hide: true
 
   pre-flight:
-      cmd: |
-        #;< FRESH_INSTALL
-        export DOCTOR_CHECK_DB=0
-        #;> FRESH_INSTALL
-        DOCTOR_CHECK_DB=${DOCTOR_CHECK_DB:-1} DOCTOR_CHECK_TOOLS=${DOCTOR_CHECK_TOOLS:-1} DOCTOR_CHECK_SSH=${DOCTOR_CHECK_SSH:-0} DOCTOR_CHECK_PORT=${DOCTOR_CHECK_PORT-:0} DOCTOR_CHECK_BOOTSTRAP=${DOCTOR_CHECK_BOOTSTRAP-:0} ahoy doctor
-      hide: true
+    cmd: |
+      #;< FRESH_INSTALL
+      export DOCTOR_CHECK_DB=0
+      #;> FRESH_INSTALL
+      DOCTOR_CHECK_DB=${DOCTOR_CHECK_DB:-1} DOCTOR_CHECK_TOOLS=${DOCTOR_CHECK_TOOLS:-1} DOCTOR_CHECK_SSH=${DOCTOR_CHECK_SSH:-0} DOCTOR_CHECK_PORT=${DOCTOR_CHECK_PORT-:0} DOCTOR_CHECK_BOOTSTRAP=${DOCTOR_CHECK_BOOTSTRAP-:0} ahoy doctor
+    hide: true
 
 entrypoint:
   - bash
@@ -274,6 +274,6 @@ entrypoint:
     #; Location of the demo database used for tests only.
     export DEMO_DB_TEST="${DEMO_DB_TEST:-https://goo.gl/6pZKHa}"
     #;> DEMO
-    bash -c "$0" "$@"
+    bash -e -c "$0" "$@"
   - '{{cmd}}'
   - '{{name}}'
