Added support for database in docker image workflow. Part 2.

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -42,7 +42,7 @@ commands:
   up:
     usage: Build and start all or specified Docker containers.
     cmd: |
-      docker-compose up -d --quiet-pull "$@" && if docker-compose logs | grep -q "\[Error\]"; then exit 1; fi
+      docker-compose up -d "$@" && if docker-compose logs | grep -q "\[Error\]"; then exit 1; fi
       #: Write Livereload host port information into a socket file.
       mkdir -p docroot/sites/default/files && docker-compose port cli 35729 | cut -d : -f 2 | xargs -I{} ahoy cli 'echo {} > /app/docroot/sites/default/files/livereload.sock'
 
@@ -109,7 +109,7 @@ commands:
     usage: Reload the database container using local database image.
     cmd: |
       ahoy confirm "Running this command will replace your current database. Are you sure?" &&
-      docker-compose rm -f -s -v mariadb && ahoy up && ahoy install-site && ahoy info && ahoy login ||
+      docker-compose rm -f -s -v mariadb && ahoy up -- --build mariadb && ahoy install-site && ahoy info && ahoy login ||
       echo "The operation was canceled."
 
   install-site:
@@ -119,8 +119,14 @@ commands:
   export-db:
     usage: Export database dump or database image (DATABASE_IMAGE variable must be set).
     cmd: |
-      [ -z "${DATABASE_IMAGE}" ] && docker-compose exec -e DB_DIR=${DB_DIR:-} -T cli ./scripts/drevops/drupal-export-db.sh "$@" ||
-      DOCKER_IMAGE="${DATABASE_IMAGE}" ./scripts/drevops/drupal-export-db-image.sh "$@"
+      [ -z "${DATABASE_IMAGE}" ] && docker-compose exec -e DB_DIR=${DB_DIR:-} -T cli ./scripts/drevops/drupal-export-db.sh "$@" || \
+      ( DOCKER_IMAGE="${DATABASE_IMAGE}" ./scripts/drevops/drupal-export-db-image.sh "$@";
+        if [ -n "${EXPORT_DB_DEPLOY_DOCKER}" ]; then DOCKER_MAP=mariadb=${DATABASE_IMAGE} ./scripts/drevops/deploy-docker.sh; fi )
+
+  pull-db:
+    usage: Download database image with the latest nightly dump. Run "ahoy reload-db" to reload DB in the running stack.
+    cmd: |
+      [ -n "${DATABASE_IMAGE}" ] && docker pull $DATABASE_IMAGE
 
   clean:
     usage: Remove containers and all build files.
